// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pfs.restful.domain;

import com.pfs.restful.domain.Faktur;
import com.pfs.restful.domain.FakturDataOnDemand;
import com.pfs.restful.domain.FakturIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FakturIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FakturIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FakturIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FakturIntegrationTest: @Transactional;
    
    @Autowired
    FakturDataOnDemand FakturIntegrationTest.dod;
    
    @Test
    public void FakturIntegrationTest.testCountFakturs() {
        Assert.assertNotNull("Data on demand for 'Faktur' failed to initialize correctly", dod.getRandomFaktur());
        long count = Faktur.countFakturs();
        Assert.assertTrue("Counter for 'Faktur' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FakturIntegrationTest.testFindFaktur() {
        Faktur obj = dod.getRandomFaktur();
        Assert.assertNotNull("Data on demand for 'Faktur' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Faktur' failed to provide an identifier", id);
        obj = Faktur.findFaktur(id);
        Assert.assertNotNull("Find method for 'Faktur' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Faktur' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FakturIntegrationTest.testFindAllFakturs() {
        Assert.assertNotNull("Data on demand for 'Faktur' failed to initialize correctly", dod.getRandomFaktur());
        long count = Faktur.countFakturs();
        Assert.assertTrue("Too expensive to perform a find all test for 'Faktur', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Faktur> result = Faktur.findAllFakturs();
        Assert.assertNotNull("Find all method for 'Faktur' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Faktur' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FakturIntegrationTest.testFindFakturEntries() {
        Assert.assertNotNull("Data on demand for 'Faktur' failed to initialize correctly", dod.getRandomFaktur());
        long count = Faktur.countFakturs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Faktur> result = Faktur.findFakturEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Faktur' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Faktur' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FakturIntegrationTest.testFlush() {
        Faktur obj = dod.getRandomFaktur();
        Assert.assertNotNull("Data on demand for 'Faktur' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Faktur' failed to provide an identifier", id);
        obj = Faktur.findFaktur(id);
        Assert.assertNotNull("Find method for 'Faktur' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFaktur(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Faktur' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FakturIntegrationTest.testMergeUpdate() {
        Faktur obj = dod.getRandomFaktur();
        Assert.assertNotNull("Data on demand for 'Faktur' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Faktur' failed to provide an identifier", id);
        obj = Faktur.findFaktur(id);
        boolean modified =  dod.modifyFaktur(obj);
        Integer currentVersion = obj.getVersion();
        Faktur merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Faktur' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FakturIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Faktur' failed to initialize correctly", dod.getRandomFaktur());
        Faktur obj = dod.getNewTransientFaktur(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Faktur' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Faktur' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Faktur' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FakturIntegrationTest.testRemove() {
        Faktur obj = dod.getRandomFaktur();
        Assert.assertNotNull("Data on demand for 'Faktur' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Faktur' failed to provide an identifier", id);
        obj = Faktur.findFaktur(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Faktur' with identifier '" + id + "'", Faktur.findFaktur(id));
    }
    
}
