// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pfs.restful.domain;

import com.pfs.restful.domain.Faktur;
import com.pfs.restful.domain.FakturDataOnDemand;
import com.pfs.restful.domain.PfsUserDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FakturDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FakturDataOnDemand: @Component;
    
    private Random FakturDataOnDemand.rnd = new SecureRandom();
    
    private List<Faktur> FakturDataOnDemand.data;
    
    @Autowired
    PfsUserDataOnDemand FakturDataOnDemand.pfsUserDataOnDemand;
    
    public Faktur FakturDataOnDemand.getNewTransientFaktur(int index) {
        Faktur obj = new Faktur();
        setCreateDate(obj, index);
        return obj;
    }
    
    public void FakturDataOnDemand.setCreateDate(Faktur obj, int index) {
        Date createDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreateDate(createDate);
    }
    
    public Faktur FakturDataOnDemand.getSpecificFaktur(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Faktur obj = data.get(index);
        Long id = obj.getId();
        return Faktur.findFaktur(id);
    }
    
    public Faktur FakturDataOnDemand.getRandomFaktur() {
        init();
        Faktur obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Faktur.findFaktur(id);
    }
    
    public boolean FakturDataOnDemand.modifyFaktur(Faktur obj) {
        return false;
    }
    
    public void FakturDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Faktur.findFakturEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Faktur' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Faktur>();
        for (int i = 0; i < 10; i++) {
            Faktur obj = getNewTransientFaktur(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
