// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pfs.restful.domain;

import com.pfs.restful.domain.FakturDataOnDemand;
import com.pfs.restful.domain.FakturItem;
import com.pfs.restful.domain.FakturItemDataOnDemand;
import com.pfs.restful.domain.MerchandiseDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FakturItemDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FakturItemDataOnDemand: @Component;
    
    private Random FakturItemDataOnDemand.rnd = new SecureRandom();
    
    private List<FakturItem> FakturItemDataOnDemand.data;
    
    @Autowired
    FakturDataOnDemand FakturItemDataOnDemand.fakturDataOnDemand;
    
    @Autowired
    MerchandiseDataOnDemand FakturItemDataOnDemand.merchandiseDataOnDemand;
    
    public FakturItem FakturItemDataOnDemand.getNewTransientFakturItem(int index) {
        FakturItem obj = new FakturItem();
        setQty(obj, index);
        return obj;
    }
    
    public void FakturItemDataOnDemand.setQty(FakturItem obj, int index) {
        int qty = index;
        obj.setQty(qty);
    }
    
    public FakturItem FakturItemDataOnDemand.getSpecificFakturItem(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        FakturItem obj = data.get(index);
        Long id = obj.getId();
        return FakturItem.findFakturItem(id);
    }
    
    public FakturItem FakturItemDataOnDemand.getRandomFakturItem() {
        init();
        FakturItem obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return FakturItem.findFakturItem(id);
    }
    
    public boolean FakturItemDataOnDemand.modifyFakturItem(FakturItem obj) {
        return false;
    }
    
    public void FakturItemDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = FakturItem.findFakturItemEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'FakturItem' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<FakturItem>();
        for (int i = 0; i < 10; i++) {
            FakturItem obj = getNewTransientFakturItem(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
