// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pfs.restful.domain;

import com.pfs.restful.domain.MerchandiseIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MerchandiseIntegrationTest_Roo_Configurable {
    
    declare @type: MerchandiseIntegrationTest: @Configurable;
    
}
