// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pfs.restful.domain;

import com.pfs.restful.domain.PfsUser;
import com.pfs.restful.domain.PfsUserDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PfsUserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PfsUserDataOnDemand: @Component;
    
    private Random PfsUserDataOnDemand.rnd = new SecureRandom();
    
    private List<PfsUser> PfsUserDataOnDemand.data;
    
    public PfsUser PfsUserDataOnDemand.getNewTransientPfsUser(int index) {
        PfsUser obj = new PfsUser();
        setPassword(obj, index);
        setUsername(obj, index);
        return obj;
    }
    
    public void PfsUserDataOnDemand.setPassword(PfsUser obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public void PfsUserDataOnDemand.setUsername(PfsUser obj, int index) {
        String username = "username_" + index;
        obj.setUsername(username);
    }
    
    public PfsUser PfsUserDataOnDemand.getSpecificPfsUser(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PfsUser obj = data.get(index);
        Long id = obj.getId();
        return PfsUser.findPfsUser(id);
    }
    
    public PfsUser PfsUserDataOnDemand.getRandomPfsUser() {
        init();
        PfsUser obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return PfsUser.findPfsUser(id);
    }
    
    public boolean PfsUserDataOnDemand.modifyPfsUser(PfsUser obj) {
        return false;
    }
    
    public void PfsUserDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PfsUser.findPfsUserEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PfsUser' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PfsUser>();
        for (int i = 0; i < 10; i++) {
            PfsUser obj = getNewTransientPfsUser(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
